Created Discount Controller and CRUD
gzili/VisualRiders.PointOfSale.Swagger pull request #1
Opened 2022-11-06 18:14 UTC by PauliusLu

2022-11-06 20:20 UTC, gzili requested changes
Nice work! There are some issues, so I left detailed explanations near the corresponding lines.

2022-11-06 20:20 UTC, gzili commented on VisualRiders.PointOfSale.Project/Controllers/DiscountsController.cs
> +        [ProducesResponseType(201)]
You were right about the magic numbers. There is actually a `StatusCodes` class that contains all HTTP status code values without the need for casting. Please replace all magic numbers with the members of this class. An example of how to use the class is in the `products` branch.

2022-11-06 20:20 UTC, gzili commented on VisualRiders.PointOfSale.Project/Models/Discount.cs
> +    public enum DiscountMeasureType
You don't have to use this `Type` suffix. A property `public DiscountMeasure DiscountMeasure { get; set; }` is perfectly valid in C#.

2022-11-06 20:20 UTC, gzili commented on VisualRiders.PointOfSale.Project/Models/Discount.cs
> +    }
A blank line after an enum declaration would be appreciated.

2022-11-06 20:20 UTC, gzili commented on VisualRiders.PointOfSale.Project/Models/Discount.cs
> +        public DiscountMeasureType DiscountMeasure { get; set; }
I already mentioned that you don't need the suffix for the type. But the `Discount` prefix is also only used to disambiguate the enum in the global type space. So, I think that this property should simply be `public DiscountMeasure Measure { get; set; }`. We already know that the measure is for the discount.

2022-11-06 20:20 UTC, gzili commented on VisualRiders.PointOfSale.Project/Models/Discount.cs
> +        public Decimal Amount { get; set; }
Decimal is a built-in C# value type, so it is preferrable to use the lowercase type alias `decimal` instead of capitalized `Decimal`. Just like with `int`, `bool`, `string`, etc.

2022-11-06 20:20 UTC, gzili commented on VisualRiders.PointOfSale.Project/Controllers/DiscountsController.cs
> +        public void UpdateById(Discount discount) {
You are not using the `id` URL parameter in the method. Also, this is debatable, but I think it is not good API design to accept the whole entity with the ID field in the request body. So, I believe that you should take in the `id` parameter in the method and then have a separate `UpdateDiscountDto` which contains the remaining fields of the `Discount` entity. I know that I have to explain this because I didn't demonstrate how to properly implement the update operation in our meeting. But now there is an example in the `products` branch which you can follow.

2022-11-06 20:20 UTC, gzili commented on VisualRiders.PointOfSale.Project/Repositories/DiscountsRepository.cs
> +        internal void Update(Discount discount)
What's this `internal` keyword for? I don't think it's needed here.

2022-11-06 20:20 UTC, gzili commented on VisualRiders.PointOfSale.Project/Repositories/DiscountsRepository.cs
> +                _discounts[i] = discount;
As I mentioned in the controller, you probably should't be replacing the old entity with user provided one. But in this case, your implementation works fine. However, I advise you to look at my implementation in the `products` branch.

2022-11-06 20:20 UTC, gzili commented on VisualRiders.PointOfSale.Project/Repositories/DiscountsRepository.cs
> +        internal void Delete(Discount discount)
Again, why the `internal` keyword?

2022-11-07 11:48 UTC, PauliusLu commented on VisualRiders.PointOfSale.Project/Controllers/DiscountsController.cs
> +        [ProducesResponseType(201)]
Yeah, I found it too when making employees API. Will change.

2022-11-07 11:49 UTC, PauliusLu commented on VisualRiders.PointOfSale.Project/Models/Discount.cs
> +    public enum DiscountMeasureType
Will change

2022-11-07 11:49 UTC, PauliusLu commented on VisualRiders.PointOfSale.Project/Models/Discount.cs
> +    }
Yes

2022-11-07 11:50 UTC, PauliusLu commented on VisualRiders.PointOfSale.Project/Models/Discount.cs
> +        public DiscountMeasureType DiscountMeasure { get; set; }
Thanks

2022-11-07 11:51 UTC, PauliusLu commented on VisualRiders.PointOfSale.Project/Models/Discount.cs
> +        public Decimal Amount { get; set; }
Fixed mistake.

2022-11-07 11:57 UTC, PauliusLu commented on VisualRiders.PointOfSale.Project/Repositories/DiscountsRepository.cs
> +        internal void Update(Discount discount)
Yeah, it was copied from Products. Fixed

2022-11-07 12:05 UTC, PauliusLu commented on VisualRiders.PointOfSale.Project/Repositories/DiscountsRepository.cs
> +        internal void Delete(Discount discount)
Answered above. Fixed

2022-11-07 12:36 UTC, PauliusLu commented on VisualRiders.PointOfSale.Project/Controllers/DiscountsController.cs
> +        public void UpdateById(Discount discount) {
Changed to use ID for identification. DTO will be added later

2022-11-07 12:37 UTC, PauliusLu commented on VisualRiders.PointOfSale.Project/Repositories/DiscountsRepository.cs
> +                _discounts[i] = discount;
Will be changed when adding DTO

2022-11-09 09:49 UTC, gzili approved these changes
Nice fixes! Thank you for considering all the comments. I can merge this as is but are you planning to implement the DTOs?

2022-11-15 15:26 UTC, merged