Implemented Employees
gzili/VisualRiders.PointOfSale.Swagger pull request #2
Opened 2022-11-06 19:52 UTC by PauliusLu

2022-11-09 10:35 UTC, gzili requested changes
Please check all the comments.

2022-11-09 10:35 UTC, gzili commented on VisualRiders.PointOfSale.Project/Controllers/EmployeesController.cs
> +        [ProducesResponseType(201)]
Magic number

2022-11-09 10:35 UTC, gzili commented on VisualRiders.PointOfSale.Project/Controllers/EmployeesController.cs
> +        [ProducesResponseType(200)]
Magic number

2022-11-09 10:35 UTC, gzili commented on VisualRiders.PointOfSale.Project/Controllers/EmployeesController.cs
> +        [ProducesResponseType(404)]
Magic number

2022-11-09 10:35 UTC, gzili commented on VisualRiders.PointOfSale.Project/Repositories/EmployeesRepository.cs
> +                Email = Guid.NewGuid().ToString().Substring(0, 5) + "@" + Guid.NewGuid().ToString().Substring(0, 5) + "." + Guid.NewGuid().ToString().Substring(0, 3),
I think that email addresses should be hardcoded. GUIDs are very long, cryptic, look awful, don't resemble real email addresses and may confuse readers.

2022-11-09 10:35 UTC, gzili commented on VisualRiders.PointOfSale.Project/Repositories/EmployeesRepository.cs
> +                Email = Guid.NewGuid().ToString().Substring(0, 5) + "@" + Guid.NewGuid().ToString().Substring(0, 5) + "." + Guid.NewGuid().ToString().Substring(0, 3),
Same issue regarding the email address format

2022-11-09 10:35 UTC, gzili commented on VisualRiders.PointOfSale.Project/Controllers/EmployeesController.cs
> +        public List<Employee> GetAll()
You should think about using a DTO that hides the password of the employee to prevent password leaks. This is necessary even when the passwords are hashed. Passwords should never be included in the responses, they should only be used on the server-side to validate logins.

2022-11-09 10:35 UTC, gzili commented on VisualRiders.PointOfSale.Project/Controllers/EmployeesController.cs
> +        public ActionResult<Employee> GetById(Guid id)
Same comment regarding the DTO. In this case you are probably ok with using the same DTO for employee list and employee details but in most cases the DTO for a single entity includes detailed information while the DTO for many entities includes only a summary of the most important data. You can look at the implementation of `RolesController` at `roles_and_permissions` branch for an example of different DTOs.

2022-11-09 10:35 UTC, gzili commented on VisualRiders.PointOfSale.Project/Controllers/EmployeesController.cs
> +        public ActionResult UpdateById(Employee employee)
We already talked that the implementation where you replace the entire entity is not ideal. You are not only blindly replacing fields which may need some logic but are also swallowing the error when an entity with the requested ID cannot be found and the update fails.

2022-11-09 10:35 UTC, gzili commented on VisualRiders.PointOfSale.Project/Controllers/EmployeesController.cs
> +            return NoContent();
I think you should return the updated employee instead of an empty body so that the client could verify that the changes were correctly applied. This is a common practice.

2022-11-09 10:35 UTC, gzili commented on VisualRiders.PointOfSale.Project/Controllers/EmployeesController.cs
> +            employee.Status = EmployeeStatus.Deleted;
Don't you think it's better to have the delete method in the repository instead of setting the property in the controller? This is internal data storage logic that probably shouldn't be visible in the controller.

2022-11-09 10:35 UTC, gzili commented on VisualRiders.PointOfSale.Project/Controllers/EmployeesController.cs
> +        public ActionResult ChangeEmployeeRole([FromRoute]Employee employee/*, [FromBody] Role role*/)
This doesn't look very clean. You should probably have a `UpdateEmployeeRoleDto` like this:
```json
{
  "roleId": "guid"
}
```
You will be able to implement the actual logic when I merge my roles branch. The example of using a DTO to update a nested field can be found [here](https://github.com/gzili/VisualRiders.PointOfSale/blob/56dc37dc4fc865becca5beaf197c9af53173e748/VisualRiders.PointOfSale.Project/Controllers/PurchasableItemsController.cs#L90).

2022-11-09 10:35 UTC, gzili commented on VisualRiders.PointOfSale.Project/Controllers/EmployeesController.cs
> +            return NoContent();
Again, you should probably return the updated employee.

2022-11-09 10:35 UTC, gzili commented on VisualRiders.PointOfSale.Project/Controllers/EmployeesController.cs
> +        public ActionResult DeleteById(Employee employee)
Why do you need the entire employee entity to delete it? Don't you only need the ID so you could find employee?

2022-11-09 10:35 UTC, gzili commented on VisualRiders.PointOfSale.Project/Controllers/EmployeesController.cs
> +                return NotFound();
I would say that this `if` block without braces and even without any blank lines to separate it looks terrible and is just asking for issues in the future. At the end, it is you choice to omit curly braces for a single-line statement but at least please separate it from the rest of the code with a blank line.
Also, the method definition does not reflect this response type.

2022-11-09 10:35 UTC, gzili commented on VisualRiders.PointOfSale.Project/Models/Employee.cs
> +        [System.ComponentModel.DataAnnotations.Key]
Why are you using the fully-qualified name for the annotation? It would be much better if you just used `[Key]`.

2022-11-09 10:35 UTC, gzili commented on VisualRiders.PointOfSale.Project/Repositories/EmployeesRepository.cs
> +        public bool Delete(Employee employee)
Again, you probably should not be asking for an entire entity just to delete it by ID.

2022-11-17 12:04 UTC, PauliusLu commented on VisualRiders.PointOfSale.Project/Controllers/EmployeesController.cs
> +        [ProducesResponseType(201)]
Fixed

2022-11-17 12:04 UTC, PauliusLu commented on VisualRiders.PointOfSale.Project/Controllers/EmployeesController.cs
> +        [ProducesResponseType(200)]
Fixed

2022-11-17 12:04 UTC, PauliusLu commented on VisualRiders.PointOfSale.Project/Controllers/EmployeesController.cs
> +        [ProducesResponseType(404)]
Fixed

2022-11-17 12:04 UTC, PauliusLu commented on VisualRiders.PointOfSale.Project/Repositories/EmployeesRepository.cs
> +                Email = Guid.NewGuid().ToString().Substring(0, 5) + "@" + Guid.NewGuid().ToString().Substring(0, 5) + "." + Guid.NewGuid().ToString().Substring(0, 3),
Ok, changed.

2022-11-17 12:05 UTC, PauliusLu commented on VisualRiders.PointOfSale.Project/Repositories/EmployeesRepository.cs
> +                Email = Guid.NewGuid().ToString().Substring(0, 5) + "@" + Guid.NewGuid().ToString().Substring(0, 5) + "." + Guid.NewGuid().ToString().Substring(0, 3),
Changed

2022-11-17 12:21 UTC, PauliusLu commented on VisualRiders.PointOfSale.Project/Controllers/EmployeesController.cs
> +        public ActionResult UpdateById(Employee employee)
Fixed. Probably implementation will change when DTO will be added.

2022-11-17 12:22 UTC, PauliusLu commented on VisualRiders.PointOfSale.Project/Controllers/EmployeesController.cs
> +            return NoContent();
Yes, good points. Thanks, fixed.

2022-11-17 12:25 UTC, PauliusLu commented on VisualRiders.PointOfSale.Project/Controllers/EmployeesController.cs
> +            employee.Status = EmployeeStatus.Deleted;
This whole method/endpoint is currently questionable due to the fact that it is HttpPut, so in essence it might be possible so enable a player. Maybe it should be HTTPDELETE. I will add this as a issue and we will discuss it later.

2022-11-17 14:03 UTC, PauliusLu commented on VisualRiders.PointOfSale.Project/Controllers/EmployeesController.cs
> +            return NoContent();
Fixed.

2022-11-17 14:05 UTC, PauliusLu commented on VisualRiders.PointOfSale.Project/Controllers/EmployeesController.cs
> +        public ActionResult DeleteById(Employee employee)
Yea, makes sense. Changed

2022-11-17 14:28 UTC, PauliusLu commented on VisualRiders.PointOfSale.Project/Controllers/EmployeesController.cs
> +                return NotFound();
It is a good practise for Guard clause not to write curly braces. Some write one line statements, some split it in two. Here is a reference https://www.davidhayden.me/blog/guard-clauses-in-computer-science and
![image](https://user-images.githubusercontent.com/29183858/202472345-62126ccc-e085-4b46-99c0-18c3864f3904.png)

Secondly, yeah, newline is missing after the check. Fixed it.
And lastly, this is likely not a guard clause, so I changed it.

2022-11-17 14:29 UTC, PauliusLu commented on VisualRiders.PointOfSale.Project/Controllers/EmployeesController.cs
> +                return NotFound();
P.S. Image refernce is here https://haacked.com/archive/2013/01/05/mitigate-the-billion-dollar-mistake-with-aspects.aspx/

2022-11-17 14:30 UTC, PauliusLu commented on VisualRiders.PointOfSale.Project/Models/Employee.cs
> +        [System.ComponentModel.DataAnnotations.Key]
Changed.

2022-11-17 14:30 UTC, PauliusLu commented on VisualRiders.PointOfSale.Project/Repositories/EmployeesRepository.cs
> +        public bool Delete(Employee employee)
Changed.

2022-11-17 20:22 UTC, PauliusLu commented on VisualRiders.PointOfSale.Project/Controllers/EmployeesController.cs
> +        public List<Employee> GetAll()
Added Dto.

2022-11-17 20:26 UTC, PauliusLu commented on VisualRiders.PointOfSale.Project/Controllers/EmployeesController.cs
> +        public ActionResult<Employee> GetById(Guid id)
Added Dto for list items too. Thanks.

2022-11-17 20:36 UTC, PauliusLu commented on VisualRiders.PointOfSale.Project/Controllers/EmployeesController.cs
> +        public ActionResult ChangeEmployeeRole([FromRoute]Employee employee/*, [FromBody] Role role*/)
Did it!

2022-11-18 16:08 UTC, gzili approved these changes

2022-11-18 16:09 UTC, merged