VR-41/Purchasable Items API
gzili/VisualRiders.PointOfSale.Swagger pull request #4
Opened 2022-11-09 14:21 UTC by GabijaG

2022-11-09 18:01 UTC, gzili requested changes
I really appreciate the work you put into this, however, there are some inconsistencies, mistakes and implementation issues. I highlighted everything that concerns me.

2022-11-09 18:01 UTC, gzili commented on VisualRiders.PointOfSale.Project/Models/ItemCathegory.cs
> +    public class ItemCathegory
Should be `ItemCategory`. There is no `h` in the word `Category`.

2022-11-09 18:01 UTC, gzili commented on VisualRiders.PointOfSale.Project/Controllers/ItemCategoriesController.cs
> +
Blank line at the start of class seems unnecessary. Especially in C#, where the curly in brace is on a new line and separates the class name from its content.

2022-11-09 18:01 UTC, gzili commented on VisualRiders.PointOfSale.Project/Controllers/ItemCategoriesController.cs
> +        [ProducesResponseType(201)]
It would be great if you could replace the magic numbers with values from the `StatusCodes` class.

2022-11-09 18:01 UTC, gzili commented on VisualRiders.PointOfSale.Project/Models/ItemCathegory.cs
> +
There should be no blank line at the end of class body.

2022-11-09 18:01 UTC, gzili commented on VisualRiders.PointOfSale.Project/Controllers/ItemCategoriesController.cs
> +        [ProducesResponseType(200)]
Can be replaced with `[ProducesDefaultResponseType]`

2022-11-09 18:01 UTC, gzili commented on VisualRiders.PointOfSale.Project/Controllers/ItemCategoriesController.cs
> +        [ProducesResponseType(404)]
Magic number

2022-11-09 18:01 UTC, gzili commented on VisualRiders.PointOfSale.Project/Controllers/ItemCategoriesController.cs
> +        public ActionResult<PurchasableItem> UpdateCathegory(ItemCathegory itemCategory)
I smell some kind of mistake here. Why is the return type `PurchasableItem`? Also, you should probably take in the ID of the category as a separate parameter from the URL and use a DTO for updating. That would be consistent with the implementations for other entities. I have comments about the issues of taking in the whole entity on Paulius' PRs and suggest taking a look at the Employees PR.

2022-11-09 18:01 UTC, gzili commented on VisualRiders.PointOfSale.Project/Controllers/ItemCategoriesController.cs
> +            if (itemCategory == null)
I don't think this can ever be `null` as the request would fail validation and this method would not be executed at all as the parameter is not nullable. I think you actually wanted to search for a category by requested ID and then perform this check to see if it could not be found.

2022-11-09 18:01 UTC, gzili commented on VisualRiders.PointOfSale.Project/Controllers/ItemCategoriesController.cs
> +                return NotFound();
In this case, you actually have a validation failure, so the `Not Found` response is incorrect. But if you fix the logic so that you try to find the category by ID, then this response will be valid. I think that's what you intended to do.

2022-11-09 18:01 UTC, gzili commented on VisualRiders.PointOfSale.Project/Controllers/ItemCategoriesController.cs
> +            return Ok();
I think you should return the updated category instead of an empty response. Just take the GMail API as an example.

2022-11-09 18:01 UTC, gzili commented on VisualRiders.PointOfSale.Project/Controllers/ItemCategoriesController.cs
> +        [ProducesResponseType(204)]
Magic number

2022-11-09 18:01 UTC, gzili commented on VisualRiders.PointOfSale.Project/Controllers/ItemCategoriesController.cs
> +        [ProducesResponseType(404)]
Magic number

2022-11-09 18:01 UTC, gzili commented on VisualRiders.PointOfSale.Project/Controllers/ItemCategoriesController.cs
> +        public ActionResult<PurchasableItem> DeleteById(Guid id)
The return type is incorrect again. In this case you are never returning any object, so the type should be `IActionResult`.

2022-11-09 18:01 UTC, gzili commented on VisualRiders.PointOfSale.Project/Controllers/ItemCategoriesController.cs
> +
Too many blank lines

2022-11-09 18:01 UTC, gzili commented on VisualRiders.PointOfSale.Project/Controllers/ItemCategoriesController.cs
> +
Too many blank lines

2022-11-09 18:01 UTC, gzili commented on VisualRiders.PointOfSale.Project/Controllers/ItemCategoriesController.cs
> +
Unnecessary blank line

2022-11-09 18:01 UTC, gzili commented on VisualRiders.PointOfSale.Project/Models/PurchasableItem.cs
> +        public Guid ItemCathegoryId { get; set; }
Cathegory

2022-11-09 18:01 UTC, gzili commented on VisualRiders.PointOfSale.Project/Controllers/PurchasableItemsController.cs
> +        [HttpGet("{status:int}")]
You should remove the template (`{status:int}`). This makes that URL `/PurchasableItems/0` returns active items and `/PurchasableItems/1` returns deleted items. This isn't what you want. You want the status to be as a query parameter like `/PurchasableItems?status=1`. For that to work, you just need a parameter in the method definition and no template. Also, I'm not sure but your current implementation may actually make the endpoint unusable as the framework would not know whether to treat the string at the end of URL as a status enum value or as a GUID as defined in the method below. The framework would not know which endpoint to use as the basically both have the same template (one string at the end of URL).

2022-11-09 18:01 UTC, gzili commented on VisualRiders.PointOfSale.Project/Controllers/PurchasableItemsController.cs
> +            if(categoryDto == null)
I'm not 100% sure but this will probably never be null as your method parameter is not nullable and framework validates that if I'm not mistaken.

2022-11-09 18:01 UTC, gzili commented on VisualRiders.PointOfSale.Project/Controllers/PurchasableItemsController.cs
> +            if (dto == null)
Again, this is probably automatically validated by the framework.

2022-11-09 18:01 UTC, gzili commented on VisualRiders.PointOfSale.Project/Repositories/ItemCathegoriesRepository.cs
> +                _itemCathegories[index] = itemCathegory;
You are replacing the entity directly with the user provided one and swallowing the error when the item cannot be updated as it doesn't exist. This probably isn't the best way to go about it.

2022-11-09 18:01 UTC, gzili commented on VisualRiders.PointOfSale.Project/Controllers/ItemCategoriesController.cs
> +            _itemCategoriesRepository.DeleteById(id);
The way you implemented your repository requires you to search for item by ID when you already found the item in the previous statement. I think the delete method of the repository should just take the item to delete.

2022-11-09 18:01 UTC, gzili commented on VisualRiders.PointOfSale.Project/Repositories/ItemCathegoriesRepository.cs
> +        public void DeleteById(Guid id)
If you passed in the actual item to delete, this would be a one line method. It is ok because you are actually searching for the item in the controller before deleting it.

2022-11-09 18:01 UTC, gzili commented on VisualRiders.PointOfSale.Project/Repositories/PurchasableItemsRepository.cs
> +            return _purchasableItems.FindAll(p => (int)p.Status == itemStatus);
When you fix the controller, you will not need any casting as you will just be able to take the enum as the method parameter.

2022-11-09 18:01 UTC, gzili commented on VisualRiders.PointOfSale.Project/Repositories/PurchasableItemsRepository.cs
> +        public void DeleteById(Guid id)
Again, if you were taking in the actual item object, you would just be able to change the status without the need to search for the item the second time. Excellent for performance and the method become one line.

2022-11-09 18:01 UTC, gzili commented on VisualRiders.PointOfSale.Project/Repositories/PurchasableItemsRepository.cs
> +            var index = _purchasableItems.FindIndex(p => p.Id == id);
Why don't you just find the item and set the status? This implementation costs you additional list access for no reason. The objects are passed by reference, so when you change a property, the new value gets reflected everywhere that object is used.

2022-11-10 14:58 UTC, GabijaG commented on VisualRiders.PointOfSale.Project/Models/ItemCathegory.cs
> +    public class ItemCathegory
I totally agree. I have done this typo too many times these past few days. 
Fixed it.

2022-11-10 15:06 UTC, GabijaG commented on VisualRiders.PointOfSale.Project/Controllers/ItemCategoriesController.cs
> +
Noted and fixed. I noticed that while coding I tend to add more of them to separate the code visually and then some get left behind.  I will try to be more careful with this next time.

2022-11-10 15:06 UTC, GabijaG commented on VisualRiders.PointOfSale.Project/Controllers/ItemCategoriesController.cs
> +
I would argue that the one in line 13-th is useful as a visual separator between the property and a constructor.  I will delete the ones on 18 and 19-th lines.

2022-11-10 15:10 UTC, GabijaG commented on VisualRiders.PointOfSale.Project/Controllers/ItemCategoriesController.cs
> +        [ProducesResponseType(201)]
Fixed.

2022-11-10 15:11 UTC, GabijaG commented on VisualRiders.PointOfSale.Project/Controllers/ItemCategoriesController.cs
> +        [ProducesResponseType(200)]
Fixed it.

2022-11-10 15:25 UTC, GabijaG commented on VisualRiders.PointOfSale.Project/Controllers/ItemCategoriesController.cs
> +        public ActionResult<PurchasableItem> UpdateCathegory(ItemCathegory itemCategory)
I agree that returning `PurchasableItem` is a mistake here - I was working on that controller at the same time. Since this was one of the first controllers I did not use dto in it - I figured out how to do it a bit later thus other controllers should have the correct implementation.

2022-11-11 08:43 UTC, GabijaG commented on VisualRiders.PointOfSale.Project/Controllers/PurchasableItemsController.cs
> +        [HttpGet("{status:int}")]
If I delete the `status` parameter from the template then the swagerUI stops working - it does not take it as a query parameter and confuses it with GetAll() endpoint which also has no parameters in the URL.

2022-11-11 08:47 UTC, GabijaG commented on VisualRiders.PointOfSale.Project/Controllers/PurchasableItemsController.cs
> +            if(categoryDto == null)
The framework does ensure that the parameter value would not be null and returns BadRequest response in such case. Thus this check is redundant

2022-11-11 08:50 UTC, GabijaG commented on VisualRiders.PointOfSale.Project/Controllers/PurchasableItemsController.cs
> +            if(categoryDto == null)
In such case, should I leave that anotiation `ProducesResponseCode(StatusCodes.Status400BadRequest)`?

2022-11-11 09:25 UTC, gzili commented on VisualRiders.PointOfSale.Project/Controllers/PurchasableItemsController.cs
> +        [HttpGet("{status:int}")]
Oh yeah, I totally overlooked that. But you agree that the current implementation is not what you are looking for? Then you have two possible solutions. You either leave one `GetAll` endpoint which accepts the `status` parameter that acts as a filter and returns all items if the `status` is not set but filters by `status` when it is set. If it is really important to have separate endpoints by status, then you have to create endpoints like `/PurchasableItems/active` and `/PurchasableItems/deleted`.

2022-11-15 15:20 UTC, gzili approved these changes

2022-11-15 15:24 UTC, merged